/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.4 */
/* Wed Oct 11 11:05:44 2017 */

/* parameterized module instance */
mcrom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
